### ISSUE TITLE
additiveDerivation asserts len(derivTags) == linCoeffs even if no linCoeffs provided

### ISSUE THREAD

**Issue by alfieadhemar** [ukaea/ReMKiT1D-Python#10]
One may not need to provide linCoeffs for an additiveDerivation however the assertion within the function definition prescribes this. A proposed change is to make a conditional statement so that if linCoeffs is provided that this assertion is checked but it is skipped if no linCoeffs are given.

**Comment by SMijin** [comment]
Resolved in PR #13
