### ISSUE TITLE
Include ability to addCustomDerivation when creating DerivationTerm (dev-v1.2.0 feature)

### ISSUE THREAD

**Issue by alfieadhemar** [ukaea/ReMKiT1D-Python#30]
Currently, utilising the new DerivationTerm object requires the customDerivation associated with said DerivationTerm to exist in the wrapper already. It would be beneficial for this to be done as a one liner by having a function that adds the necessary customDerivation before then creating a DerivationTerm

**Comment by SMijin** [comment]
No longer relevant with v2.0.0
