### ISSUE TITLE
v2.0.0 logLii latexTemplate argument bug

### ISSUE THREAD

**Issue by sleigh2022** [ukaea/ReMKiT1D-Python#47]
- In derivations.py `Textbook.__getitem__`, when defining an ion-ion Coulomb log variable ("logLii"), invoking the textbook variable "logLii" raises the following assertion error:

```
AssertionError: $2 not in latexTemplate
```

- This is because logLii has 4 arguments - 2 densities and 2 temperatures for each of the 2 ion species - but when the Derivation super() object is initialised, it tries to loop over 4 numArgs to generate the latexTemplate, but the latexTemplate itself only contains references to 2 arguments `$0` and `$1`.

- A quick fix is to simply change the last line of the logLii GenericDerivation latexTemplate arg from: `"}\\left($0,$1\\right)"` to `"}\\left($0,$1,$2,$3\\right)"`.

- It would be good to discuss if there should be any additional changes to the way the super() object is generated, i.e. how the number of arguments to the Derivation relates to the number of arguments in its latexTemplate.

**Comment by SMijin** [comment]
Fixed with the proposed quick fix. Start discussion of LaTeX improvement in the feature megathread if needed.
